### ISSUE TITLE
problem installing

### ISSUE THREAD

**Issue by nelson2005** [jprjr/netstring.lua#1]
I'm trying to get going with lua-resty-exec, when I run 'luarocks install lua-resty-exec' it tries to install netstring, which fails with 

Error: Failed installing dependency: https://luarocks.org/netstring-1.0.2-0.rockspec - 'git' program not found. Make sure Git is installed and is available in your PATH (or you may want to edit the 'variables.GIT' value in file '/app/users/enelson/openresty-1.11.2.2/luajit/etc/luarocks/config-5.1.lua')

I don't have git available on my machine, is there any alternative install process?  The openresty install process didn't require it.

Thanks

**Comment by jprjr** [comment]
I modified the rockspec so you shouldn't need git installed - give it a try and let me know if that works

**Comment by nelson2005** [comment]
It works great!  Thanks much!

**Comment by jprjr** [comment]
No problem!
